### ISSUE TITLE
Fix the rounded Image

### ISSUE THREAD

**Issue by Devkant21** [Devkant21/ct#2]
https://github.com/Devkant21/ct/blob/main/src/components/Body.jsx

Image is in the asset folder
Image not loading
<img width="1455" alt="Screen Shot 2022-03-13 at 7 48 04 PM" src="https://user-images.githubusercontent.com/40569250/158063619-80fcfc8d-5d05-4ac6-bce2-96d6b384f668.png">

**Comment by AtarioPZ** [comment]
Import image from assets directory
`import profilepic from '../assets/dd.jpg'`
And 
<img className='w-24 h-24 rounded-full mx-6'  `src={profilepic}`  alt="" width="400" height="400"/>

**Comment by Devkant21** [comment]
Thanks @AtarioPZ . Good Job.  I'll close the issue.
